server:
  port: 9090
  servlet:
    context-path: /
  error:
    include-stacktrace: never
spring:
  application:
    name: nowprj-be
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    database: H2
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      globally_quoted_identifiers: true
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
    path: /doc/openapi.yaml
  show-actuator: true
  cache:
    disabled: true
